[package]
name = "stage-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.8", package = "gtk4", features = ["v4_14"] }
adw = { version = "0.6", package = "libadwaita", features = ["v1_5"] }

vte4 = { version = "0.7", package = "vte" }

rdw = { package = "rdw4",               path = "./rdw/rdw4" }
rdw-spice = { package = "rdw4-spice",   path = "./rdw/rdw4-spice" }
rdw-vnc = { package = "rdw4-vnc",       path = "./rdw/rdw4-vnc" }
