[package]
name = "field-monitor-proxmox"
edition.workspace = true
rust-version.workspace = true

[dependencies]
libfieldmonitor = { path = "../../lib" }
gettext-rs = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { version = "1.40", features = ["parking_lot", "rt"] }
reqwest = "0.12"
log = { workspace = true }
gtk = { workspace = true }
adw = { workspace = true }
vte = { workspace = true }
secure-string = { workspace = true }

[lints]
workspace = true